//
// Generated file, do not edit! Created by nedtool 5.5 from Customer.msg.
//

#ifndef __CUSTOMER_M_H
#define __CUSTOMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Customer.msg:16</tt> by nedtool.
 * <pre>
 * message Customer
 * {
 *     double cartLength;
 *     simtime_t arrivalTime;
 * }
 * </pre>
 */
class Customer : public ::omnetpp::cMessage
{
  protected:
    double cartLength;
    ::omnetpp::simtime_t arrivalTime;

  private:
    void copy(const Customer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Customer&);

  public:
    Customer(const char *name=nullptr, short kind=0);
    Customer(const Customer& other);
    virtual ~Customer();
    Customer& operator=(const Customer& other);
    virtual Customer *dup() const override {return new Customer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getCartLength() const;
    virtual void setCartLength(double cartLength);
    virtual ::omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(::omnetpp::simtime_t arrivalTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Customer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Customer& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CUSTOMER_M_H

